import type { ConverterTool } from './types';

export const CONVERTER_TOOLS: ConverterTool[] = [
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert every PDF page to high-quality JPG images.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'zip',
    multiple: false,
    maxFiles: 1,
    icon: 'FileImage',
    color: 'from-rose-500 to-orange-500',
    popular: true,
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Export PDF pages as transparent-ready PNG files.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'zip',
    multiple: false,
    maxFiles: 1,
    icon: 'FileImage',
    color: 'from-violet-500 to-purple-500',
    popular: true,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Combine JPG images into a single PDF document.',
    category: 'pdf',
    accept: ['image/jpeg', 'image/jpg'],
    acceptLabel: 'JPG',
    output: 'pdf',
    multiple: true,
    maxFiles: 50,
    icon: 'FileText',
    color: 'from-red-500 to-rose-500',
    popular: true,
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description: 'Merge PNG images into one PDF file.',
    category: 'pdf',
    accept: ['image/png'],
    acceptLabel: 'PNG',
    output: 'pdf',
    multiple: true,
    maxFiles: 50,
    icon: 'FileText',
    color: 'from-indigo-500 to-blue-500',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable DOCX format.',
    category: 'office',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'docx',
    multiple: false,
    maxFiles: 1,
    icon: 'FileType',
    color: 'from-blue-600 to-cyan-500',
    popular: true,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert DOCX/DOC files to PDF instantly.',
    category: 'office',
    accept: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
    ],
    acceptLabel: 'Word',
    output: 'pdf',
    multiple: true,
    maxFiles: 20,
    icon: 'FileText',
    color: 'from-sky-500 to-blue-600',
    popular: true,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert spreadsheets to print-ready PDF.',
    category: 'office',
    accept: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
    ],
    acceptLabel: 'Excel',
    output: 'pdf',
    multiple: true,
    maxFiles: 20,
    icon: 'Sheet',
    color: 'from-emerald-500 to-green-600',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from PDF into XLSX.',
    category: 'office',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'xlsx',
    multiple: false,
    maxFiles: 1,
    icon: 'Sheet',
    color: 'from-green-500 to-teal-500',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint presentations to PDF.',
    category: 'office',
    accept: [
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.ms-powerpoint',
    ],
    acceptLabel: 'PowerPoint',
    output: 'pdf',
    multiple: true,
    maxFiles: 20,
    icon: 'Presentation',
    color: 'from-orange-500 to-amber-500',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PPT',
    description: 'Convert PDF slides to editable PPTX.',
    category: 'office',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pptx',
    multiple: false,
    maxFiles: 1,
    icon: 'Presentation',
    color: 'from-amber-500 to-yellow-500',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Render HTML files as PDF documents.',
    category: 'office',
    accept: ['text/html'],
    acceptLabel: 'HTML',
    output: 'pdf',
    multiple: true,
    maxFiles: 10,
    icon: 'Code',
    color: 'from-slate-600 to-slate-800',
  },
  {
    id: 'txt-to-pdf',
    name: 'TXT to PDF',
    description: 'Convert plain text files to formatted PDF.',
    category: 'pdf',
    accept: ['text/plain'],
    acceptLabel: 'TXT',
    output: 'pdf',
    multiple: true,
    maxFiles: 20,
    icon: 'AlignLeft',
    color: 'from-gray-500 to-zinc-600',
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce image file size without losing clarity.',
    category: 'image',
    accept: ['image/jpeg', 'image/png', 'image/webp', 'image/jpg'],
    acceptLabel: 'Images',
    output: 'same',
    multiple: true,
    maxFiles: 30,
    icon: 'Minimize2',
    color: 'from-teal-500 to-emerald-500',
    popular: true,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Optimize PDF size for email and upload.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pdf',
    multiple: true,
    maxFiles: 10,
    icon: 'Shrink',
    color: 'from-red-600 to-rose-600',
    popular: true,
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one file.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pdf',
    multiple: true,
    maxFiles: 30,
    icon: 'Combine',
    color: 'from-red-500 to-pink-500',
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Split PDF into separate pages or ranges.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'zip',
    multiple: false,
    maxFiles: 1,
    icon: 'Split',
    color: 'from-orange-600 to-red-500',
    popular: true,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate all or selected PDF pages.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pdf',
    multiple: false,
    maxFiles: 1,
    icon: 'RotateCw',
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text watermark to your PDF.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pdf',
    multiple: false,
    maxFiles: 1,
    icon: 'Droplets',
    color: 'from-cyan-500 to-blue-500',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDF.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pdf',
    multiple: false,
    maxFiles: 1,
    icon: 'Unlock',
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password encryption to your PDF.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'pdf',
    multiple: false,
    maxFiles: 1,
    icon: 'Lock',
    color: 'from-amber-600 to-orange-600',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'AI-powered text extraction from scanned PDFs.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'txt',
    multiple: false,
    maxFiles: 1,
    icon: 'ScanText',
    color: 'from-purple-600 to-violet-600',
    popular: true,
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract readable text from PDF files.',
    category: 'pdf',
    accept: ['application/pdf'],
    acceptLabel: 'PDF',
    output: 'txt',
    multiple: false,
    maxFiles: 1,
    icon: 'FileText',
    color: 'from-slate-500 to-gray-600',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    description: 'Convert JPG images to PNG format.',
    category: 'image',
    accept: ['image/jpeg', 'image/jpg'],
    acceptLabel: 'JPG',
    output: 'image',
    multiple: true,
    maxFiles: 30,
    icon: 'Image',
    color: 'from-pink-500 to-rose-500',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG images to JPG format.',
    category: 'image',
    accept: ['image/png'],
    acceptLabel: 'PNG',
    output: 'image',
    multiple: true,
    maxFiles: 30,
    icon: 'Image',
    color: 'from-yellow-500 to-orange-500',
  },
  {
    id: 'webp-to-jpg',
    name: 'WEBP to JPG',
    description: 'Convert WEBP images to JPG.',
    category: 'image',
    accept: ['image/webp'],
    acceptLabel: 'WEBP',
    output: 'image',
    multiple: true,
    maxFiles: 30,
    icon: 'Image',
    color: 'from-lime-500 to-green-500',
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WEBP',
    description: 'Convert JPG to modern WEBP format.',
    category: 'image',
    accept: ['image/jpeg', 'image/jpg'],
    acceptLabel: 'JPG',
    output: 'image',
    multiple: true,
    maxFiles: 30,
    icon: 'Image',
    color: 'from-green-400 to-teal-500',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert iPhone HEIC photos to JPG.',
    category: 'image',
    accept: ['image/heic', 'image/heif'],
    acceptLabel: 'HEIC',
    output: 'image',
    multiple: true,
    maxFiles: 30,
    icon: 'Smartphone',
    color: 'from-blue-400 to-indigo-500',
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Rasterize SVG vector graphics to PNG.',
    category: 'image',
    accept: ['image/svg+xml'],
    acceptLabel: 'SVG',
    output: 'image',
    multiple: true,
    maxFiles: 20,
    icon: 'PenTool',
    color: 'from-fuchsia-500 to-purple-500',
  },
  {
    id: 'batch-convert',
    name: 'Batch Convert',
    description: 'Process multiple files in one queue job.',
    category: 'utility',
    accept: ['*/*'],
    acceptLabel: 'Any',
    output: 'zip',
    multiple: true,
    maxFiles: 50,
    icon: 'Layers',
    color: 'from-indigo-600 to-violet-600',
    popular: true,
  },
];

export function getToolById(id: string): ConverterTool | undefined {
  return CONVERTER_TOOLS.find((t) => t.id === id);
}

export const POPULAR_TOOLS = CONVERTER_TOOLS.filter((t) => t.popular);

export const TOOLS_BY_CATEGORY = {
  pdf: CONVERTER_TOOLS.filter((t) => t.category === 'pdf'),
  image: CONVERTER_TOOLS.filter((t) => t.category === 'image'),
  office: CONVERTER_TOOLS.filter((t) => t.category === 'office'),
  utility: CONVERTER_TOOLS.filter((t) => t.category === 'utility'),
};
